# Generated by Django 5.2.5 on 2026-01-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_cart_id_order_cart_snapshot"),
        ("order_payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="cart_id",
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="order.order",
            ),
        ),
    ]
