# Generated by Django 5.2.5 on 2026-01-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_payment", "0002_remove_paymenttransaction_cart_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
