# Generated by Django 5.2.5 on 2026-01-11 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStockCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("max_capacity", models.PositiveIntegerField(default=100)),
                ("available_capacity", models.PositiveIntegerField(default=100)),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_capacity",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["effective_date"], name="stock_and_c_effecti_d92cbd_idx"
                    ),
                    models.Index(
                        fields=["product", "effective_date"],
                        name="stock_and_c_product_76df1c_idx",
                    ),
                ],
                "unique_together": {("product", "effective_date")},
            },
        ),
    ]
