# Generated by Django 5.2.5 on 2026-01-11 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product की price उस समय की",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "db_table": "cart_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_active_cart_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_active_cart_per_session",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_user_id_2c8a21_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_session_81d746_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_cart_status_39ba2f_idx",
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CONVERTED", "Converted to Order"),
                    ("ABANDONED", "Abandoned"),
                    ("EXPIRED", "Expired"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="product.product",
            ),
        ),
    ]
