# Generated by Django 5.2.5 on 2026-01-25 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0003_order_email_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("STRIPE", "Stripe"), ("GST", "GST")], max_length=20
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stripe_invoice_pdf", models.URLField(blank=True, null=True)),
                ("gstin", models.CharField(max_length=20)),
                ("hsn_code", models.CharField(max_length=10)),
                ("cgst", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sgst", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("GENERATED", "Generated")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
        ),
    ]
