# Generated by Django 5.2.5 on 2026-01-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
        ("order", "0003_order_email_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="cgst",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="gstin",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="hsn_code",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="sgst",
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("STRIPE", "Stripe")], default="STRIPE", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("GENERATED", "Generated"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
