# Generated by Django 5.2.5 on 2026-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_cart_id_order_cart_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
