# Generated by Django 5.2.5 on 2026-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
